name: Start GitHub Actions

on:
  push:
    branches: [main]

jobs:
  test-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Test 1
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

    - name: Run Tests
      run: javac App.java